doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '13' # Adjust according to your MySQL version
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
