nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000'] # Set your React app's URL here
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': # Enable CORS for routes under /api/ or adjust to your needs
            allow_origin: ['http://localhost:3000']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
