# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['*']  # Change '*' to your frontend URL in production
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'OPTIONS']
        max_age: 3600  # Optional: specify how long the results of a preflight request can be cached
    paths:
        '^/api/':  # Adjust this path to match your API routes
            allow_origin: ['*']  # Again, specify your frontend URL in production
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'OPTIONS']
