security:
    password_hashers:
        App\Entity\User:
            algorithm: auto  # Automatically select the best hashing algorithm

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true  # Important for API-based authentication
            provider: app_user_provider
            # Use 'lazy: true' to allow unauthenticated access and defer authentication until needed
            lazy: true
            
            # Logout configuration
            logout:
                path: app_logout
                target: app_home

    access_control:
        # Define access rules
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow registration without authentication
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
