security:
    # Hashers
    password_hashers:
        App\Entity\User:
            algorithm: auto  # Automatically selects the best algorithm

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true  # Important for API-based authentication
            provider: app_user_provider
            lazy: true
            
            logout:
                path: app_logout
                target: app_home
            custom_authenticator: App\Security\AuthControllerAuthenticator

    access_control:
        # Allow access to the registration and login routes without authentication
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
