security:
    # Use 'password_hashers' instead of 'encoders'
    password_hashers:
        App\Entity\User:
            algorithm: auto  # This will automatically select the best hashing algorithm

    providers:
        app_user_provider:
            # Define the user provider, usually fetching from a database entity
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # If you are building an API, set this to true
            stateless: true  # Important for API-based authentication
            # Uncomment the authentication method you intend to use
            # form_login:
            #     login_path: login
            #     check_path: login
            #     # other options...
            # If using JWT or token-based auth, configure here as well

    access_control:
        # Define access rules
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow registration without authentication
        # Add more access rules as needed
