security:
    # Use 'password_hashers' instead of 'encoders'
    password_hashers:
        App\Entity\User:
            algorithm: auto  # This will automatically select the best hashing algorithm

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # If you are building an API, set this to true
            stateless: true  # Important for API-based authentication

            # Allow anonymous access
            anonymous: true
            
            # Specify the provider to use
            provider: app_user_provider

            # Logout configuration
            logout:
                path: app_logout
                target: app_home

    access_control:
        # Define access rules
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Allow registration without authentication
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
